function h = plot_paper_curve(x, y, styleIndex, markerIdx, varargin)
%PLOT_PAPER_CURVE Plot one series using the shared paper color palette.
style = paper_curve_style(styleIndex);
h = plot(x, y, ...
    'Color', style.color, ...
    'LineStyle', style.lineStyle, ...
    'Marker', style.marker, ...
    'LineWidth', 1.25, ...
    'MarkerSize', 5, ...
    'MarkerIndices', markerIdx, ...
    varargin{:});
end
